package com.showerideas.aura.utils

import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyProperties
import timber.log.Timber
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import javax.crypto.Cipher
import javax.crypto.KeyAgreement
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Cryptographic utilities for AURA.
 *
 * Exchange flow:
 * 1. Each peer generates an ephemeral ECDH keypair per session.
 * 2. Public keys are exchanged over the Nearby Connections plaintext channel.
 * 3. Both sides derive the same shared AES-256 session key via ECDH.
 * 4. Profile payload is encrypted with AES-GCM before transmission.
 *
 * The long-lived device identity key (for endpoint verification) lives in
 * the Android Keystore under alias [KEYSTORE_ALIAS_DEVICE_ID].
 */
object CryptoUtils {

    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEYSTORE_ALIAS_DEVICE_ID = "aura_device_identity"
    private const val AES_GCM_ALGORITHM = "AES/GCM/NoPadding"
    private const val AES_KEY_SIZE = 256
    private const val GCM_IV_SIZE = 12
    private const val GCM_TAG_SIZE = 128

    // -------------------------------------------------------------------------
    // Ephemeral ECDH (per-session key agreement)
    // -------------------------------------------------------------------------

    /**
     * Generate a fresh ephemeral EC keypair for one exchange session.
     * NEVER reuse the same keypair across sessions.
     */
    fun generateEphemeralECDHKeyPair(): KeyPair {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(256)
        return kpg.generateKeyPair()
    }

    /**
     * Derive a shared 256-bit AES key from our private key and the peer's public key.
     *
     * NIST SP 800-56A compliance: raw ECDH output is never used directly as a key.
     * HKDF-SHA256 (RFC 5869) is applied to the shared secret so the AES key is
     * uniformly distributed and domain-separated from the raw EC point coordinates.
     */
    fun deriveSharedAESKey(ourPrivateKey: PrivateKey, peerPublicKey: PublicKey): SecretKey {
        val ka = KeyAgreement.getInstance("ECDH")
        ka.init(ourPrivateKey)
        ka.doPhase(peerPublicKey, true)
        val sharedSecret = ka.generateSecret()

        val salt = "AURA-ECDH-v1".toByteArray(Charsets.UTF_8)
        val info = "aes-256-gcm-session-key".toByteArray(Charsets.UTF_8)

        // HKDF-Extract: PRK = HMAC-SHA256(salt, sharedSecret)
        val hmacExtract = Mac.getInstance("HmacSHA256")
        hmacExtract.init(SecretKeySpec(salt, "HmacSHA256"))
        val prk = hmacExtract.doFinal(sharedSecret)

        // HKDF-Expand: OKM = HMAC-SHA256(PRK, info || 0x01)  — one block, 32 bytes
        val hmacExpand = Mac.getInstance("HmacSHA256")
        hmacExpand.init(SecretKeySpec(prk, "HmacSHA256"))
        hmacExpand.update(info)
        hmacExpand.update(0x01.toByte())
        val okm = hmacExpand.doFinal()  // 32 bytes

        // Zero-fill sensitive intermediates before GC can observe them.
        sharedSecret.fill(0)
        prk.fill(0)

        return SecretKeySpec(okm, "AES")
    }

    // -------------------------------------------------------------------------
    // AES-GCM encryption / decryption
    // -------------------------------------------------------------------------

    /**
     * Encrypt [plaintext] with [key] using AES-256-GCM.
     * Returns IV (12 bytes) + ciphertext + tag (16 bytes) concatenated.
     */
    fun encrypt(key: SecretKey, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_GCM_ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // Random 12-byte IV generated by the Cipher
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext
    }

    /**
     * Decrypt a blob produced by [encrypt].
     */
    fun decrypt(key: SecretKey, blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_SIZE) { "Blob too short to contain IV" }
        val iv = blob.copyOf(GCM_IV_SIZE)
        val ciphertext = blob.copyOfRange(GCM_IV_SIZE, blob.size)
        val cipher = Cipher.getInstance(AES_GCM_ALGORITHM)
        val spec = GCMParameterSpec(GCM_TAG_SIZE, iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        return cipher.doFinal(ciphertext)
    }

    // -------------------------------------------------------------------------
    // Android Keystore — long-lived device identity
    // -------------------------------------------------------------------------

    /**
     * Get or create the device identity keypair in the Android Keystore.
     * Used to sign challenge tokens during peer authentication.
     */
    // -------------------------------------------------------------------------
    // ECDSA challenge / response (PR-13)
    //
    // The device identity key returned by [getOrCreateDeviceIdentityKey] is
    // long-lived. We sign random per-session challenges with it so the peer
    // can prove they hold the same private key they presented as part of
    // any prior pairing. This catches MITM endpoint substitution and
    // tampered re-binds of an endpoint ID to a different identity.
    // -------------------------------------------------------------------------

    /**
     * Sign a 32-byte random challenge with the device's long-lived ECDSA
     * key. Uses SHA256withECDSA — supported by the secp256r1 keys we
     * generate in [getOrCreateDeviceIdentityKey].
     */
    fun signChallenge(privateKey: PrivateKey, challenge: ByteArray): ByteArray {
        return Signature.getInstance("SHA256withECDSA").apply {
            initSign(privateKey)
            update(challenge)
        }.sign()
    }

    /**
     * Verify a signature produced by [signChallenge]. Returns false on any
     * crypto failure (bad signature, wrong key, malformed bytes) — callers
     * must treat false as a hard rejection.
     */
    fun verifyChallenge(publicKey: PublicKey, challenge: ByteArray, signature: ByteArray): Boolean {
        return runCatching {
            Signature.getInstance("SHA256withECDSA").apply {
                initVerify(publicKey)
                update(challenge)
            }.verify(signature)
        }.getOrDefault(false)
    }

    /**
     * FIX-5: stable, device-agnostic fingerprint of a peer's identity public key.
     *
     * SHA-256 over the X.509-encoded key bytes, Base64-encoded. Used as the
     * blocklist key instead of the ephemeral Nearby endpoint ID so that a
     * blocked device cannot bypass the block simply by reconnecting with a
     * new session (which always gets a fresh endpoint ID).
     */
    fun identityKeyHash(publicKey: PublicKey): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256")
        return java.util.Base64.getEncoder().encodeToString(digest.digest(publicKey.encoded))
    }

    fun getOrCreateDeviceIdentityKey(): KeyPair {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
        if (!ks.containsAlias(KEYSTORE_ALIAS_DEVICE_ID)) {
            Timber.d("Creating new device identity key in Keystore")
            val spec = KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS_DEVICE_ID,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setAlgorithmParameterSpec(java.security.spec.ECGenParameterSpec("secp256r1"))
                .setDigests(KeyProperties.DIGEST_SHA256, KeyProperties.DIGEST_SHA512)
                .setUserAuthenticationRequired(false) // Exchange speed > bio-auth here
                .build()

            KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE_PROVIDER)
                .apply { initialize(spec) }
                .generateKeyPair()
        }
        val privateKey = ks.getKey(KEYSTORE_ALIAS_DEVICE_ID, null) as PrivateKey
        val publicKey = ks.getCertificate(KEYSTORE_ALIAS_DEVICE_ID).publicKey
        return KeyPair(publicKey, privateKey)
    }
}
