package com.showerideas.aura.utils

import android.os.Build
import android.security.keystore.KeyGenParameterSpec
import android.security.keystore.KeyInfo
import android.security.keystore.KeyProperties
import timber.log.Timber
import java.security.KeyFactory
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.KeyStore
import java.security.PrivateKey
import java.security.PublicKey
import java.security.Signature
import javax.crypto.Cipher
import javax.crypto.KeyAgreement
import javax.crypto.KeyGenerator
import javax.crypto.Mac
import javax.crypto.SecretKey
import javax.crypto.spec.GCMParameterSpec
import javax.crypto.spec.SecretKeySpec

/**
 * Cryptographic utilities for AURA.
 *
 * Exchange flow:
 * 1. Each peer generates an ephemeral ECDH keypair per session.
 * 2. Public keys are exchanged over the Nearby Connections plaintext channel.
 * 3. Both sides derive the same shared AES-256 session key via ECDH.
 * 4. Profile payload is encrypted with AES-GCM before transmission.
 *
 * The long-lived device identity key (for endpoint verification) lives in
 * the Android Keystore under alias [KEYSTORE_ALIAS_DEVICE_ID].
 */
object CryptoUtils {

    private const val KEYSTORE_PROVIDER = "AndroidKeyStore"
    private const val KEYSTORE_ALIAS_DEVICE_ID = "aura_device_identity"
    private const val AES_GCM_ALGORITHM = "AES/GCM/NoPadding"
    private const val AES_KEY_SIZE = 256
    private const val GCM_IV_SIZE = 12
    private const val GCM_TAG_SIZE = 128

    // -------------------------------------------------------------------------
    // Ephemeral ECDH (per-session key agreement)
    // -------------------------------------------------------------------------

    /**
     * Generate a fresh ephemeral EC keypair for one exchange session.
     * NEVER reuse the same keypair across sessions.
     */
    fun generateEphemeralECDHKeyPair(): KeyPair {
        val kpg = KeyPairGenerator.getInstance("EC")
        kpg.initialize(256)
        return kpg.generateKeyPair()
    }

    /**
     * Derive a shared 256-bit AES key from our private key and the peer's public key.
     *
     * NIST SP 800-56A compliance: raw ECDH output is never used directly as a key.
     * HKDF-SHA256 (RFC 5869) is applied to the shared secret so the AES key is
     * uniformly distributed and domain-separated from the raw EC point coordinates.
     */
    fun deriveSharedAESKey(ourPrivateKey: PrivateKey, peerPublicKey: PublicKey): SecretKey {
        val ka = KeyAgreement.getInstance("ECDH")
        ka.init(ourPrivateKey)
        ka.doPhase(peerPublicKey, true)
        val sharedSecret = ka.generateSecret()

        val salt = "AURA-ECDH-v1".toByteArray(Charsets.UTF_8)
        val info = "aes-256-gcm-session-key".toByteArray(Charsets.UTF_8)

        // HKDF-Extract: PRK = HMAC-SHA256(salt, sharedSecret)
        val hmacExtract = Mac.getInstance("HmacSHA256")
        hmacExtract.init(SecretKeySpec(salt, "HmacSHA256"))
        val prk = hmacExtract.doFinal(sharedSecret)

        // HKDF-Expand: OKM = HMAC-SHA256(PRK, info || 0x01)  — one block, 32 bytes
        val hmacExpand = Mac.getInstance("HmacSHA256")
        hmacExpand.init(SecretKeySpec(prk, "HmacSHA256"))
        hmacExpand.update(info)
        hmacExpand.update(0x01.toByte())
        val okm = hmacExpand.doFinal()  // 32 bytes

        // Zero-fill sensitive intermediates before GC can observe them.
        sharedSecret.fill(0)
        prk.fill(0)

        return SecretKeySpec(okm, "AES")
    }

    // -------------------------------------------------------------------------
    // AES-GCM encryption / decryption
    // -------------------------------------------------------------------------

    /**
     * Encrypt [plaintext] with [key] using AES-256-GCM.
     * Returns IV (12 bytes) + ciphertext + tag (16 bytes) concatenated.
     */
    fun encrypt(key: SecretKey, plaintext: ByteArray): ByteArray {
        val cipher = Cipher.getInstance(AES_GCM_ALGORITHM)
        cipher.init(Cipher.ENCRYPT_MODE, key)
        val iv = cipher.iv  // Random 12-byte IV generated by the Cipher
        val ciphertext = cipher.doFinal(plaintext)
        return iv + ciphertext
    }

    /**
     * Decrypt a blob produced by [encrypt].
     */
    fun decrypt(key: SecretKey, blob: ByteArray): ByteArray {
        require(blob.size > GCM_IV_SIZE) { "Blob too short to contain IV" }
        val iv = blob.copyOf(GCM_IV_SIZE)
        val ciphertext = blob.copyOfRange(GCM_IV_SIZE, blob.size)
        val cipher = Cipher.getInstance(AES_GCM_ALGORITHM)
        val spec = GCMParameterSpec(GCM_TAG_SIZE, iv)
        cipher.init(Cipher.DECRYPT_MODE, key, spec)
        return cipher.doFinal(ciphertext)
    }

    // -------------------------------------------------------------------------
    // Android Keystore — long-lived device identity
    // -------------------------------------------------------------------------

    /**
     * Get or create the device identity keypair in the Android Keystore.
     * Used to sign challenge tokens during peer authentication.
     */
    // -------------------------------------------------------------------------
    // ECDSA challenge / response
    //
    // The device identity key returned by [getOrCreateDeviceIdentityKey] is
    // long-lived. We sign random per-session challenges with it so the peer
    // can prove they hold the same private key they presented as part of
    // any prior pairing. This catches MITM endpoint substitution and
    // tampered re-binds of an endpoint ID to a different identity.
    // -------------------------------------------------------------------------

    /**
     * Sign a 32-byte random challenge with the device's long-lived ECDSA
     * key. Uses SHA256withECDSA — supported by the secp256r1 keys we
     * generate in [getOrCreateDeviceIdentityKey].
     */
    fun signChallenge(privateKey: PrivateKey, challenge: ByteArray): ByteArray {
        return Signature.getInstance("SHA256withECDSA").apply {
            initSign(privateKey)
            update(challenge)
        }.sign()
    }

    /**
     * Verify a signature produced by [signChallenge]. Returns false on any
     * crypto failure (bad signature, wrong key, malformed bytes) — callers
     * must treat false as a hard rejection.
     */
    fun verifyChallenge(publicKey: PublicKey, challenge: ByteArray, signature: ByteArray): Boolean {
        return runCatching {
            Signature.getInstance("SHA256withECDSA").apply {
                initVerify(publicKey)
                update(challenge)
            }.verify(signature)
        }.getOrDefault(false)
    }

    /**
     * stable, device-agnostic fingerprint of a peer's identity public key.
     *
     * SHA-256 over the X.509-encoded key bytes, Base64-encoded. Used as the
     * blocklist key instead of the ephemeral Nearby endpoint ID so that a
     * blocked device cannot bypass the block simply by reconnecting with a
     * new session (which always gets a fresh endpoint ID).
     */
    fun identityKeyHash(publicKey: PublicKey): String {
        val digest = java.security.MessageDigest.getInstance("SHA-256")
        return java.util.Base64.getEncoder().encodeToString(digest.digest(publicKey.encoded))
    }

    // -------------------------------------------------------------------------
    // Sub-key derivation (directional key separation)
    // -------------------------------------------------------------------------

    /**
     * Derive a domain-separated 256-bit AES sub-key from an existing [SecretKey].
     *
     * Used to create *directional* ratchet seeds so that the initiator's send key
     * and the responder's send key are cryptographically independent even though
     * both are derived from the same ECDH session key:
     *
     * ```
     * sendRatchetSeed = deriveSubkey(sessionKey, "aura-init-send")
     * recvRatchetSeed = deriveSubkey(sessionKey, "aura-init-recv")
     * ```
     *
     * The peer uses the symmetric labelling:
     * - Their sendRatchet = our recvRatchet seed  ("aura-init-recv")
     * - Their recvRatchet = our sendRatchet seed  ("aura-init-send")
     *
     * This gives forward secrecy at the per-message level within a session, and
     * ensures profile payloads travelling in opposite directions use different keys.
     */
    fun deriveSubkey(key: SecretKey, label: String): SecretKey {
        val hmac = Mac.getInstance("HmacSHA256")
        hmac.init(key)
        hmac.update(label.toByteArray(Charsets.UTF_8))
        return SecretKeySpec(hmac.doFinal(), "AES")
    }

    // -------------------------------------------------------------------------
    // Double Ratchet helpers (thin wrappers — main logic in DoubleRatchetState)
    // -------------------------------------------------------------------------

    /**
     * Create a new [DoubleRatchetState] seeded from an ECDH-derived session key.
     *
     * Convenience so callers don't need to import [DoubleRatchetState] separately.
     *
     * Usage:
     * ```kotlin
     * val sessionKey = deriveSharedAESKey(myPrivateKey, peerPublicKey)
     * val ratchet    = CryptoUtils.newRatchet(sessionKey)
     * val msgKey     = ratchet.nextMessageKey()          // per-payload key
     * val cipher     = encrypt(msgKey, plaintext)        // send this
     * ```
     */
    fun newRatchet(sessionKey: SecretKey): DoubleRatchetState =
        DoubleRatchetState.from(sessionKey)

    /**
     * Encrypt [plaintext] using a fresh ratchet key derived from [ratchet].
     *
     * Convenience combination of [DoubleRatchetState.nextMessageKey] + [encrypt].
     * Returns IV + ciphertext blob (same format as [encrypt]).
     */
    fun ratchetEncrypt(ratchet: DoubleRatchetState, plaintext: ByteArray): ByteArray =
        encrypt(ratchet.nextMessageKey(), plaintext)

    /**
     * Decrypt a blob produced by [ratchetEncrypt] using a fresh key from [ratchet].
     *
     * The receiver's ratchet must be in the same step as the sender's.
     */
    fun ratchetDecrypt(ratchet: DoubleRatchetState, blob: ByteArray): ByteArray =
        decrypt(ratchet.nextMessageKey(), blob)

    // -------------------------------------------------------------------------
    // Android Keystore — long-lived device identity
    // -------------------------------------------------------------------------

    /**
     * Get or create the device identity keypair in the Android Keystore.
     *
     * Prefers StrongBox (dedicated Secure Element, physically isolated from main CPU — e.g.
     * Google Titan M on Pixel 2+, Samsung's embedded SE). Falls back silently to the standard
     * TEE-backed Keystore if StrongBox is unavailable.
     *
     * The StrongBox vs TEE distinction matters: StrongBox keys are immune to
     * root-level extraction, side-channel attacks on the application processor, and
     * Spectre/Meltdown-class hardware vulnerabilities. Where available, use it.
     */
    fun getOrCreateDeviceIdentityKey(): KeyPair {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
        if (!ks.containsAlias(KEYSTORE_ALIAS_DEVICE_ID)) {
            Timber.d("Creating new device identity key — trying StrongBox first")
            // Try StrongBox (API 28+, hardware-isolated Secure Element)
            val created = tryCreateIdentityKey(strongBox = true)
                ?: tryCreateIdentityKey(strongBox = false)
            if (created == null) error("Failed to create device identity key in Keystore")
            Timber.d("Device identity key created successfully")
        }
        val privateKey = ks.getKey(KEYSTORE_ALIAS_DEVICE_ID, null) as PrivateKey
        val publicKey  = ks.getCertificate(KEYSTORE_ALIAS_DEVICE_ID).publicKey
        return KeyPair(publicKey, privateKey)
    }

    private fun tryCreateIdentityKey(strongBox: Boolean): KeyPair? {
        return try {
            val specBuilder = KeyGenParameterSpec.Builder(
                KEYSTORE_ALIAS_DEVICE_ID,
                KeyProperties.PURPOSE_SIGN or KeyProperties.PURPOSE_VERIFY
            )
                .setAlgorithmParameterSpec(java.security.spec.ECGenParameterSpec("secp256r1"))
                .setDigests(KeyProperties.DIGEST_SHA256, KeyProperties.DIGEST_SHA512)
                .setUserAuthenticationRequired(false)
            if (strongBox && Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
                specBuilder.setIsStrongBoxBacked(true)
            }
            KeyPairGenerator.getInstance(KeyProperties.KEY_ALGORITHM_EC, KEYSTORE_PROVIDER)
                .apply { initialize(specBuilder.build()) }
                .generateKeyPair()
                .also {
                    if (strongBox) Timber.i("Identity key secured in StrongBox (dedicated SE)")
                    else           Timber.d("Identity key secured in TEE (StrongBox unavailable)")
                }
        } catch (e: Exception) {
            if (strongBox) Timber.d("StrongBox unavailable — falling back to TEE: ${e.message}")
            else           Timber.e(e, "TEE key creation also failed")
            null
        }
    }

    /**
     * Returns true if the device identity key is backed by a StrongBox Secure Element
     * (as opposed to the software TEE). Useful for surfacing a "hardware-secured" trust
     * badge in the UI.
     *
     * Requires API 31+ to distinguish StrongBox from TEE via [KeyInfo.getSecurityLevel].
     * Returns false on older API levels (key may still be hardware-backed TEE, just
     * indistinguishable without the SecurityLevel API).
     */
    fun isIdentityKeyStrongBoxBacked(): Boolean {
        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.S) return false
        return try {
            val ks  = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }
            val key = ks.getKey(KEYSTORE_ALIAS_DEVICE_ID, null) as? PrivateKey ?: return false
            val ki  = KeyFactory.getInstance(key.algorithm, KEYSTORE_PROVIDER)
                .getKeySpec(key, KeyInfo::class.java)
            // KeyProperties.SecurityLevel is an @IntDef annotation, not a class.
            // Access its constants directly on KeyProperties (API 31+).
            @Suppress("NewApi") // guarded by Build.VERSION check above
            ki.securityLevel == KeyProperties.SECURITY_LEVEL_STRONGBOX
        } catch (e: Exception) {
            Timber.d("Could not determine StrongBox backing: ${e.message}")
            false
        }
    }

    // -------------------------------------------------------------------------
    // Key rotation (Phase 6.5)
    // -------------------------------------------------------------------------

    /**
     * Rotate the device identity key.
     *
     * Sequence:
     * 1. Get the current identity [KeyPair] (to sign the rotation certificate).
     * 2. Delete the existing Keystore alias.
     * 3. Generate a new identity key under the same alias via [getOrCreateDeviceIdentityKey].
     * 4. Sign `newPublicKey.encoded || timestampBytes` with the OLD private key
     *    to produce a [RotationCertificate] that proves continuity of identity.
     *
     * The rotation certificate is returned so callers can:
     * - Persist it in [KnownPeer.rotationCertificate] for outbound broadcast.
     * - Pass it to [IdentityRotationDetector] on the receiving side.
     *
     * @return [RotationCertificate] containing the new public key bytes and the
     *         ECDSA signature over them produced by the old private key.
     * @throws SecurityException if the Keystore operation fails.
     */
    fun rotateDeviceIdentityKey(): RotationCertificate {
        val ks = KeyStore.getInstance(KEYSTORE_PROVIDER).also { it.load(null) }

        // 1. Get current key (need private key for signing before deletion)
        val oldKeyPair = getOrCreateDeviceIdentityKey()
        val oldPrivateKey = ks.getKey(KEYSTORE_ALIAS_DEVICE_ID, null) as PrivateKey

        // 2. Delete old alias
        ks.deleteEntry(KEYSTORE_ALIAS_DEVICE_ID)
        Timber.i("Identity key rotation: old key deleted from Keystore")

        // 3. Generate new key under the same alias
        val newKeyPair = getOrCreateDeviceIdentityKey()
        val newPublicKeyBytes = newKeyPair.public.encoded
        Timber.i("Identity key rotation: new key created")

        // 4. Sign (newPublicKeyBytes || bigEndianTimestamp) with the old private key
        val timestamp = System.currentTimeMillis()
        val timestampBytes = java.nio.ByteBuffer.allocate(8).putLong(timestamp).array()
        val payload = newPublicKeyBytes + timestampBytes

        val signature = java.security.Signature.getInstance("SHA256withECDSA").run {
            initSign(oldPrivateKey)
            update(payload)
            sign()
        }
        Timber.i("Identity key rotation: rotation certificate signed (${signature.size} bytes)")

        return RotationCertificate(
            oldPublicKeyBytes = oldKeyPair.public.encoded,
            newPublicKeyBytes = newPublicKeyBytes,
            signatureBytes    = signature,
            rotatedAtMs       = timestamp
        )
    }

    /**
     * A rotation certificate proving that the holder of the old identity key
     * authorises the new key as their legitimate successor.
     *
     * Wire format (for [KnownPeer.rotationCertificate]):
     * Serialise as DER or JSON — the service layer handles encoding.
     */
    data class RotationCertificate(
        /** X.509 SPKI bytes of the old identity public key. */
        val oldPublicKeyBytes: ByteArray,
        /** X.509 SPKI bytes of the new identity public key. */
        val newPublicKeyBytes: ByteArray,
        /** ECDSA-SHA256 signature over (newPublicKeyBytes || bigEndianTimestamp). */
        val signatureBytes: ByteArray,
        /** Epoch ms when the rotation occurred. */
        val rotatedAtMs: Long
    ) {
        override fun equals(other: Any?) = other is RotationCertificate &&
                oldPublicKeyBytes.contentEquals(other.oldPublicKeyBytes) &&
                newPublicKeyBytes.contentEquals(other.newPublicKeyBytes) &&
                signatureBytes.contentEquals(other.signatureBytes) &&
                rotatedAtMs == other.rotatedAtMs
        override fun hashCode() = oldPublicKeyBytes.contentHashCode()
    }
}
