package com.showerideas.aura.service

import android.app.Activity
import android.app.PendingIntent
import android.content.Intent
import android.content.IntentFilter
import android.nfc.NdefMessage
import android.nfc.NdefRecord
import android.nfc.NfcAdapter
import android.nfc.Tag
import android.nfc.tech.Ndef
import android.nfc.tech.NdefFormatable
import timber.log.Timber
import java.io.IOException
import java.security.PublicKey
import java.util.Base64

/**
 * NFC tap-to-exchange helper — AURA's third transport path.
 *
 * ## Why NFC?
 * NFC contact sharing completes in < 1 second and requires no pairing, no Wi-Fi,
 * and no Play Services. Compared to BLE/Wi-Fi P2P (Nearby Connections) and QR codes,
 * a physical tap feels the most intentional and private — both parties must be
 * present within centimetres of each other.
 *
 * Inspired by: BLEMeshChat in-person key verification, LocalSend's multi-transport
 * approach, and Android's own Quick Share UX principles (tap-to-send first).
 *
 * ## What is transmitted over NFC
 * Only the ephemeral ECDH public key + session UUID (< 200 bytes). The full
 * encrypted contact bundle is exchanged over Nearby Connections once both peers
 * have derived a shared AES key from the NFC-bootstrapped public keys.
 *
 * ## NDEF record format
 * ```
 * MIME type: application/vnd.aura.key-bootstrap
 * Payload:   <sessionUuid>\n<base64-encoded public key bytes>
 * ```
 *
 * ## HCE path
 * When this device acts as the **card** (peer's phone is the reader), the
 * exchange is handled by [AuraHceService] via ISO 7816-4 APDUs. Call
 * [AuraHceService.setLocalKey] before starting the session so the HCE
 * service can serve the public key to the reader.
 *
 * ## NDEF path (reader/tag path)
 * When this device acts as the **reader** (or the peer uses a writable NFC tag),
 * enable foreground dispatch with [enable], then parse incoming intents with
 * [handleIntent].
 *
 * ## Typical activity integration
 * ```kotlin
 * // In onResume:
 * NfcExchangeHelper.enable(this, myPublicKey.encoded, sessionId)
 * AuraHceService.setLocalKey(sessionId, myPublicKey.encoded)
 *
 * // In onPause:
 * NfcExchangeHelper.disable(this)
 * AuraHceService.clearLocalKey()
 *
 * // In onNewIntent:
 * val bootstrap = NfcExchangeHelper.handleIntent(intent)
 * if (bootstrap != null) { /* derive shared key, start exchange */ }
 * ```
 *
 * ## Permissions
 * Declare in AndroidManifest.xml (already present in AURA):
 * ```xml
 * <uses-permission android:name="android.permission.NFC" />
 * <uses-feature android:name="android.hardware.nfc" android:required="false" />
 * <uses-feature android:name="android.hardware.nfc.hce" android:required="false" />
 * ```
 * `required="false"` keeps the app available on devices without NFC; all functions
 * below no-op gracefully when NFC is unavailable.
 */
object NfcExchangeHelper {

    /** NDEF MIME type identifying AURA key-bootstrap records. */
    const val MIME_TYPE = "application/vnd.aura.key-bootstrap"

    /**
     * Minimum acceptable public key byte length.
     * Accepts compressed EC P-256 (33 bytes) and larger formats.
     */
    private const val MIN_KEY_BYTES = 32

    // ─────────────────────────────────────────────────────────────────────
    // Data types
    // ─────────────────────────────────────────────────────────────────────

    /**
     * The result of a successful NFC tap — the peer's ephemeral ECDH public key
     * and the session UUID they generated.
     */
    data class NfcBootstrap(
        /** Session UUID generated by the peer (used to de-dupe duplicate intents). */
        val peerSessionUuid: String,
        /** Raw public-key bytes of the peer's ephemeral ECDH public key. */
        val peerPublicKeyBytes: ByteArray
    ) {
        override fun equals(other: Any?): Boolean {
            if (this === other) return true
            if (other !is NfcBootstrap) return false
            return peerSessionUuid == other.peerSessionUuid &&
                   peerPublicKeyBytes.contentEquals(other.peerPublicKeyBytes)
        }
        override fun hashCode(): Int =
            31 * peerSessionUuid.hashCode() + peerPublicKeyBytes.contentHashCode()
    }

    // ─────────────────────────────────────────────────────────────────────
    // Lifecycle — call from Activity.onResume / onPause
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Enable NFC foreground dispatch for [activity].
     *
     * @param activity   The foreground activity.
     * @param keyBytes   Our ephemeral ECDH public key bytes (written to tags we initiate).
     * @param sessionId  Our session UUID written alongside our key in the NDEF payload.
     */
    fun enable(activity: Activity, keyBytes: ByteArray, sessionId: String) {
        val adapter = NfcAdapter.getDefaultAdapter(activity)
        if (adapter == null) {
            Timber.d("NFC: adapter not available on this device")
            return
        }
        if (!adapter.isEnabled) {
            Timber.d("NFC: adapter is disabled by user — skipping foreground dispatch")
            return
        }

        val pendingIntent = PendingIntent.getActivity(
            activity,
            REQUEST_CODE_NFC,
            Intent(activity, activity.javaClass).addFlags(Intent.FLAG_ACTIVITY_SINGLE_TOP),
            PendingIntent.FLAG_MUTABLE or PendingIntent.FLAG_UPDATE_CURRENT
        )

        val mimeFilter = IntentFilter(NfcAdapter.ACTION_NDEF_DISCOVERED).apply {
            try { addDataType(MIME_TYPE) } catch (e: IntentFilter.MalformedMimeTypeException) {
                Timber.e(e, "NFC: bad MIME type in intent filter — programming error")
            }
        }

        runCatching {
            adapter.enableForegroundDispatch(
                activity,
                pendingIntent,
                arrayOf(mimeFilter),
                null
            )
            Timber.d("NFC foreground dispatch enabled (session=$sessionId)")
        }.onFailure { Timber.e(it, "NFC: failed to enable foreground dispatch") }
    }

    /**
     * Enable NFC foreground dispatch using a [PublicKey] directly.
     * Convenience overload that extracts the encoded bytes automatically.
     */
    fun enable(activity: Activity, localKey: PublicKey, sessionId: String) =
        enable(activity, localKey.encoded, sessionId)

    /**
     * Disable NFC foreground dispatch. Call in [Activity.onPause].
     * Safe no-op if NFC is unavailable.
     */
    fun disable(activity: Activity) {
        NfcAdapter.getDefaultAdapter(activity)?.runCatching {
            disableForegroundDispatch(activity)
            Timber.d("NFC foreground dispatch disabled")
        }
    }

    // ─────────────────────────────────────────────────────────────────────
    // Intent handling — call from Activity.onNewIntent
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Parse an incoming NFC [Intent] and extract the peer's key bootstrap data.
     *
     * @return [NfcBootstrap] on success; null if the intent is not an AURA NFC tap.
     */
    fun handleIntent(intent: Intent): NfcBootstrap? {
        val action = intent.action
        if (action != NfcAdapter.ACTION_NDEF_DISCOVERED &&
            action != NfcAdapter.ACTION_TAG_DISCOVERED &&
            action != NfcAdapter.ACTION_TECH_DISCOVERED
        ) return null

        @Suppress("DEPRECATION")
        val rawMessages = intent.getParcelableArrayExtra(NfcAdapter.EXTRA_NDEF_MESSAGES)
        if (rawMessages != null) {
            for (raw in rawMessages) {
                val msg = raw as? NdefMessage ?: continue
                parseNdefMessage(msg)?.let { return it }
            }
        }

        val tag = intent.getParcelableExtra<Tag>(NfcAdapter.EXTRA_TAG) ?: return null
        return readFromTag(tag)
    }

    // ─────────────────────────────────────────────────────────────────────
    // Tag read/write helpers
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Read an AURA NDEF record from [tag].
     */
    fun readFromTag(tag: Tag): NfcBootstrap? {
        val ndef = Ndef.get(tag) ?: return null
        return try {
            ndef.connect()
            val message = ndef.ndefMessage
            ndef.close()
            message?.let { parseNdefMessage(it) }
        } catch (e: IOException) {
            Timber.e(e, "NFC: failed to read NDEF from tag")
            runCatching { ndef.close() }
            null
        }
    }

    /**
     * Write our ephemeral ECDH public key to an NFC tag.
     *
     * @param tag       The NFC tag to write.
     * @param keyBytes  Our ephemeral ECDH public key bytes.
     * @param sessionId Our session UUID.
     * @return true if the write succeeded; false otherwise.
     */
    fun writeToTag(tag: Tag, keyBytes: ByteArray, sessionId: String): Boolean {
        val message = buildNdefMessage(sessionId, keyBytes) ?: return false

        Ndef.get(tag)?.let { ndef ->
            return try {
                ndef.connect()
                val ok = ndef.isWritable && ndef.maxSize >= message.toByteArray().size
                if (ok) ndef.writeNdefMessage(message)
                ndef.close()
                if (ok) Timber.d("NFC: wrote key bootstrap to Ndef tag (session=$sessionId)")
                ok
            } catch (e: IOException) {
                Timber.e(e, "NFC: Ndef write failed")
                runCatching { ndef.close() }
                false
            }
        }

        NdefFormatable.get(tag)?.let { formatable ->
            return try {
                formatable.connect()
                formatable.format(message)
                formatable.close()
                Timber.d("NFC: formatted tag and wrote key bootstrap (session=$sessionId)")
                true
            } catch (e: IOException) {
                Timber.e(e, "NFC: NdefFormatable write failed")
                runCatching { formatable.close() }
                false
            }
        }

        Timber.w("NFC: tag supports neither Ndef nor NdefFormatable — cannot write")
        return false
    }

    /**
     * Convenience overload accepting a [PublicKey].
     */
    fun writeToTag(tag: Tag, localKey: PublicKey, sessionId: String): Boolean =
        writeToTag(tag, localKey.encoded, sessionId)

    // ─────────────────────────────────────────────────────────────────────
    // Public NDEF build / parse — exposed for HCE parity and testing
    // ─────────────────────────────────────────────────────────────────────

    /**
     * Build an AURA NDEF message containing [sessionId] and [keyBytes].
     *
     * @return [NdefMessage] on success; null if [keyBytes] is empty.
     */
    fun buildNdefMessage(sessionId: String, keyBytes: ByteArray): NdefMessage? {
        if (keyBytes.isEmpty()) return null
        val payload = "$sessionId\n${Base64.getEncoder().encodeToString(keyBytes)}"
        val record  = NdefRecord.createMime(MIME_TYPE, payload.toByteArray(Charsets.UTF_8))
        return NdefMessage(arrayOf(record))
    }

    /**
     * Parse an AURA [NdefMessage] and return the embedded [NfcBootstrap].
     *
     * @return [NfcBootstrap] on success; null if the message contains no valid AURA record.
     */
    fun parseNdefMessage(message: NdefMessage): NfcBootstrap? {
        for (record in message.records) {
            val mimeType = String(record.type, Charsets.UTF_8)
            if (!mimeType.equals(MIME_TYPE, ignoreCase = true)) continue

            val payload = String(record.payload, Charsets.UTF_8)
            val parts   = payload.split("\n", limit = 2)
            if (parts.size < 2) {
                Timber.w("NFC: malformed AURA NDEF record — missing newline separator")
                continue
            }

            val sessionUuid = parts[0].trim()
            val keyBytesB64 = parts[1].trim()
            val keyBytes = runCatching {
                Base64.getDecoder().decode(keyBytesB64)
            }.onFailure {
                Timber.w("NFC: failed to base64-decode peer public key")
            }.getOrNull() ?: continue

            if (keyBytes.size < MIN_KEY_BYTES) {
                Timber.w("NFC: peer public key too short (${keyBytes.size} bytes) — rejecting")
                continue
            }

            return NfcBootstrap(sessionUuid, keyBytes)
        }
        return null
    }

    // ─────────────────────────────────────────────────────────────────────
    // Private
    // ─────────────────────────────────────────────────────────────────────

    private const val REQUEST_CODE_NFC = 0xA57A  // "AURA"
}
